# Generated by Django 4.2.4 on 2023-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='react_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
