# Generated by Django 4.2.4 on 2023-11-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_react_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='react_type',
        ),
    ]
