# Generated by Django 4.2.4 on 2023-12-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_delete_notification'),
        ('notification', '0003_remove_notification_react_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='react',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reply',
        ),
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
    ]
