# Generated by Django 4.2.4 on 2023-12-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('react', '0001_initial'),
        ('comment', '0006_delete_notification'),
        ('reply', '0001_initial'),
        ('notification', '0004_remove_notification_react_remove_notification_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='react',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='react.react'),
        ),
        migrations.AddField(
            model_name='notification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reply.reply'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
    ]
