# Generated by Django 4.2.4 on 2023-12-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_countnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='author',
            field=models.IntegerField(null=True),
        ),
    ]
