# Generated by Django 4.2.4 on 2023-12-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_rename_author_notification_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='background',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='countnotification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
