# Generated by Django 4.2.4 on 2023-12-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_notification_background_alter_countnotification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='profile_avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
