# Generated by Django 4.2.4 on 2023-11-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
