# Generated by Django 4.2.4 on 2023-11-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_notification_comment_alter_notification_react'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
